config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :home
   devise_for :users
   resources :users, only: [:index, :update] do
      member do
        delete :removed
      end
   end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :password, :remember_me])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :password, :remember_me])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @incomplete_tasks = Task.where(complete: false)
    @complete_tasks = Task.where(complete: true)
  end

  def new
    @task = Task.new
  end

  def create
  	@task = Task.create!(allowed_params)

  	respond_to do |f|
  	f.html { redirect_to tasks_url }
  	f.js
  	end
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes!(allowed_params)

    respond_to do |f|
      f.html { redirect_to tasks_url }
      f.js
    end
  end


 def destroy
   @task = Task.destroy(params[:id])

   respond_to do |f|
     f.html { redirect_to tasks_url }
     f.js
   end
 end

  private

  def allowed_params
    params.require(:task).permit(:name, :complete)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    @not_admin = User.where(admin: false)
    @admin = User.where(admin: true)
    @superadmin = User.where(superadmin: true)
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes!(allowed_params)

    respond_to do |f|
      f.html { redirect_to users_url }
      f.js
    end
  end

 def removed
   @user = User.destroy(params[:id])

   respond_to do |f|
     f.html { redirect_to users_url }
     f.js
   end
 end


  private

  def allowed_params
    params.require(:user).permit(:name, :email, :admin, :superadmin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
  <!-- to render an html page from another use the render tag -->
  <!-- <%= render 'layouts/toolbar' %> -->
<div class="marginadjust">
  <h1> Welcome to the Website Home Page </h1>
  <h2> Go to home.scss and turn on the @import statements to see the effects of the hidden css </h2>

  <!-- MapMarker -->
  <div class='pin'></div>
  <div class='pulse'></div>

  <!--Opacity -->
  <div class="pulsate">I can fade in and out</div>

  <div class="confirm_selection" style="overflow-x: hidden; overflow-y: hidden; opacity: 1; ">[ Hover Over me to give me a red shadow ]</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sharebox2</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
  </head>

  <body>
    <div id="root" props= <%= user_signed_in?.to_s %> ></div>
    <!-- <link href="https://fonts.googleapis.com/css?family=EB+Garamond" rel="stylesheet"> -->
    <%= yield %>
  </body>
</html>

<%= javascript_pack_tag 'application' %>

<script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>

app/views/tasks/_form.html.erb
<%= form_for @task, remote: true do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/tasks/_task.html.erb
<%= form_for task, remote: true do |f| %>
  <div class="toggle-btn">
    <%= f.check_box :complete, class:"cb-value taskComplete#{task.complete}" %>
    <span class="round-btn"></span>
    <%= f.submit "Update", task:"submititem" %>
  </div>
  <%= f.label :complete, task.name %>
  <%= link_to "Remove", task, method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
<% end %>

app/views/tasks/create.js.erb
$('#new_task').remove();
$('#new_link').show();
$('#incomplete_tasks').append('<%= j render(@task) %>');
$('#edit_task_<%= @task.id %>').submitOnCheck();

app/views/tasks/destroy.js.erb
$('#edit_task_<%= @task.id %>').remove();

app/views/tasks/index.html.erb
<div class="marginadjust">  
  <h1>Task Log</h1>
  <%= link_to "New Task", new_task_path, id: "new_link", remote: true %>
  <h2>Incomplete Tasks</h2>
  <div class="tasks" id="incomplete_tasks">
    <%= render @incomplete_tasks %>
  </div>
  <h2>Complete Tasks</h2>
  <div class="tasks" id="complete_tasks">
    <%= render @complete_tasks %>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>
<%= render 'form' %>
<p><%= link_to "Back to tasks", tasks_path %></p>

app/views/tasks/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/tasks/update.js.erb
<% if @task.complete? %>
  $('#edit_task_<%= @task.id %>').appendTo('#complete_tasks');
<% else %>
  $('#edit_task_<%= @task.id %>').appendTo('#incomplete_tasks');
<% end %> 

app/views/users/_user.html.erb
<!-- in order to dynamically change the id you can include the ruby tag with a .to_s to convert it to a string -->

<%= form_for user, remote: true do |f| %>
    <% if current_user.superadmin %>
    <div class="toggle-btn">
      <%= f.check_box :superadmin, class:"cb-value superAdmin#{user.superadmin}" %>
      <span class="round-btn"></span>
      <%= f.submit "Update", task:"submititem" %>
    </div>
    <div class="toggle-btn">
      <%= f.check_box :admin, class:"cb-value Admin#{user.admin}", value: user.admin? %>
      <span class="round-btn"></span>
    </div>
      <%= f.label :admin, user.name %>
      <%= f.label :admin, user.email %>
      <%= link_to "Remove", removed_user_path(user), :method => :delete, data: {confirm: "Are you sure?"}, remote: true %>
    <% elsif current_user.admin? && !current_user.superadmin %>
      <%= f.check_box :superadmin, class:"cb-value", isChecked: user.superadmin, disabled: true %>>
      <%= f.submit "Update", task:"submititem", disabled: true %>
        <%= f.check_box :admin, class:"cb-value", isChecked: user.admin, disabled: true %>
      <%= f.submit "Update", task:"submititem", disabled: true %>
      <%= f.label :admin, user.name %>
      <%= f.label :admin, user.email %>
      <%= link_to "Remove", removed_user_path(user), :method => :post, data: {confirm: "Are you sure?"},remote: true %>
   <% else %>
      <%= f.label :admin, user.name %>
      <%= f.label :admin, user.email %>
  <% end %>
<% end %>

app/views/users/index.html.erb
<div class="marginadjust">
  <h1>List of All Users</h1>
  <%= render @users %>
</div>

app/views/users/removed.js.erb
$('#edit_user_<%= @user.id %>').remove();